version: "3"
services:
  app_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
